name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/Api src/Application src/Domain src/Infrastructure src/Worker
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build -c Release

  docker-staging:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }}:staging .
          docker push ${{ secrets.DOCKER_IMAGE }}:staging

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    needs: docker-staging
    runs-on: ubuntu-latest
    steps:
      - name: (example) Deploy staging
        run: echo "Deploy to staging here (compose or k8s)"