# Enterprise Fullstack Orchestrator - Docker Compose
# Coordinates shared infrastructure for Web and API templates

services:
  # === Shared Database ===
  postgres:
    image: postgres:16
    container_name: enterprisefullstack-postgres-${ENV:-dev}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-enterprisefullstack_dev}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASS:-app}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data_${ENV:-dev}:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-app} -d ${POSTGRES_DB:-enterprisefullstack_dev}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev
      - staging
      - prod

  # === Shared Redis Cache ===
  redis:
    image: redis:7-alpine
    container_name: enterprisefullstack-redis-${ENV:-dev}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data_${ENV:-dev}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev
      - staging
      - prod

  # === Shared Message Queue ===
  rabbitmq:
    image: rabbitmq:3-management
    container_name: enterprisefullstack-rabbitmq-${ENV:-dev}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-app}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-app}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data_${ENV:-dev}:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 30s
      retries: 3
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev
      - staging
      - prod

  # === Shared Observability Stack ===

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: enterprisefullstack-otel-${ENV:-dev}
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "${OTEL_GRPC_PORT:-4317}:4317" # OTLP gRPC receiver
      - "${OTEL_HTTP_PORT:-4318}:4318" # OTLP HTTP receiver
    depends_on:
      - jaeger
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev
      - staging
      - prod

  # Jaeger Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: enterprisefullstack-jaeger-${ENV:-dev}
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev
      - staging
      - prod

  # Seq Structured Logging
  seq:
    image: datalust/seq:latest
    container_name: enterprisefullstack-seq-${ENV:-dev}
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "${SEQ_PORT:-5341}:80"
    volumes:
      - seq_data_${ENV:-dev}:/data
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev
      - staging
      - prod

  # === Development Tools ===

  # Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: enterprisefullstack-pgadmin-${ENV:-dev}
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data_${ENV:-dev}:/var/lib/pgadmin
    depends_on:
      - postgres
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev
      - staging

  # Email Testing (Development only)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: enterprisefullstack-mailhog-${ENV:-dev}
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
      - "${MAILHOG_UI_PORT:-8025}:8025"
    profiles:
      - fullstack
      - web-infra
      - backend-infra
      - dev

  # === Application Services ===

  # Web Application (Blazor)
  web:
    build:
      context: ./${WEB_PROJECT:-WEB_PROJECT_NAME}
      dockerfile: Dockerfile
    container_name: enterprisefullstack-web-${ENV:-dev}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: "http://+:80"
      # Database connection
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=${POSTGRES_DB:-enterprisefullstack_dev};Username=${DB_USER:-app};Password=${DB_PASS:-app}"
      # API backend URL
      Backend__ApiUrl: ${API_URL:-http://api:80}
      # Observability endpoints
      Seq__ServerUrl: http://seq:80
      OpenTelemetry__Endpoint: http://otel-collector:4317
    ports:
      - "${WEB_HTTP_PORT:-3000}:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
      otel-collector:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - fullstack
      - web-infra
      - dev
      - staging
      - prod

  # API Application (Clean Architecture)
  api:
    build:
      context: ./${API_PROJECT:-API_PROJECT_NAME}
      dockerfile: Dockerfile
    container_name: enterprisefullstack-api-${ENV:-dev}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      # Database connection
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=${POSTGRES_DB:-enterprisefullstack_dev};Username=${DB_USER:-app};Password=${DB_PASS:-app}"
      # Redis cache
      Redis__ConnectionString: redis:6379
      # RabbitMQ
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: ${RABBITMQ_USER:-app}
      RabbitMq__Password: ${RABBITMQ_PASS:-app}
      # Observability
      Seq__ServerUrl: http://seq:80
      OpenTelemetry__Endpoint: http://otel-collector:4317
    ports:
      - "${API_HTTP_PORT:-5100}:80"
      - "${API_HTTPS_PORT:-5101}:443"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_started
      otel-collector:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - fullstack
      - backend-infra
      - dev
      - staging
      - prod

# === Shared Volumes ===
volumes:
  postgres_data_dev:
    name: enterprisefullstack-postgres-dev
  postgres_data_staging:
    name: enterprisefullstack-postgres-staging
  postgres_data_prod:
    name: enterprisefullstack-postgres-prod

  redis_data_dev:
    name: enterprisefullstack-redis-dev
  redis_data_staging:
    name: enterprisefullstack-redis-staging
  redis_data_prod:
    name: enterprisefullstack-redis-prod

  rabbitmq_data_dev:
    name: enterprisefullstack-rabbitmq-dev
  rabbitmq_data_staging:
    name: enterprisefullstack-rabbitmq-staging
  rabbitmq_data_prod:
    name: enterprisefullstack-rabbitmq-prod

  seq_data_dev:
    name: enterprisefullstack-seq-dev
  seq_data_staging:
    name: enterprisefullstack-seq-staging
  seq_data_prod:
    name: enterprisefullstack-seq-prod

  pgadmin_data_dev:
    name: enterprisefullstack-pgadmin-dev
  pgadmin_data_staging:
    name: enterprisefullstack-pgadmin-staging
  pgadmin_data_prod:
    name: enterprisefullstack-pgadmin-prod

# === Networks ===
networks:
  default:
    name: enterprisefullstack-network-${ENV:-dev}
    driver: bridge
