services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: ["dev", "staging", "prod"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    profiles: ["dev", "staging"]

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "${RABBIT_AMQP_PORT:-5672}:5672"
      - "${RABBIT_MGMT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s
    profiles: ["dev", "staging", "prod"]

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    profiles: ["dev", "staging", "prod"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s

  otel:
    image: jaegertracing/all-in-one:1.57
    restart: always
    ports:
      - "${OTEL_UI_PORT:-16686}:16686"
      - "${OTLP_GRPC_PORT:-4317}:4317"
      - "${OTLP_HTTP_PORT:-4318}:4318"
    profiles: ["dev", "staging", "prod"]

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - "${SMTP_PORT:-1025}:1025"
      - "${MAILHOG_UI_PORT:-8025}:8025"
    profiles: ["dev", "staging", "prod"]

  seq:
    image: datalust/seq:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "${SEQ_PORT:-5341}:80"
    volumes:
      - seq-data:/data
    profiles: ["dev", "staging", "prod"]

volumes:
  pgdata: {}
  pgadmin-data: {}
  seq-data: {}
