services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: enterprise
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports: ["5050:80"]
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: ["6672:5672", "16672:15672"] # Custom external port, standard internal port
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app

  redis:
    image: redis:7
    restart: always
    ports: ["6379:6379"]

  jaeger:
    image: jaegertracing/all-in-one:1.57
    restart: always
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports: ["1025:1025", "8025:8025"]

  seq:
    image: datalust/seq:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports: ["5341:80"]
    volumes:
      - seq-data:/data

volumes:
  pgdata: {}
  pgadmin-data: {}
  seq-data: {}
